-- On Omarchy this file is GENERATED by the OS-wide theme switcher, which is
-- why it is absent from their repo. Nothing writes it here, so it is pinned to
-- the theme this machine already uses everywhere else (fzf, p10k, the shell).
return {
  { "catppuccin/nvim", name = "catppuccin", priority = 1000 },
  { "LazyVim/LazyVim", opts = { colorscheme = "catppuccin-mocha" } },
}
